# parent image
FROM python:3.9-slim-buster

# Copy app
COPY . /usr/src/app

# install FreeTDS and dependencies
RUN apt-get update \
 && apt-get install unixodbc -y \
 && apt-get install unixodbc-dev -y \
 && apt-get install freetds-dev -y \
 && apt-get install freetds-bin -y \
 && apt-get install tdsodbc -y \
 && apt-get install --reinstall build-essential -y

# populate "ocbcinst.ini"
RUN echo "[FreeTDS]\n\
Description = FreeTDS unixODBC Driver\n\
Driver = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so\n\
Setup = /usr/lib/x86_64-linux-gnu/odbc/libtdsS.so" >> /etc/odbcinst.ini

# set working directory
WORKDIR /usr/src/app

# install dependencies
RUN pip install -r requirements.txt

# run app.py upon container launch
ENTRYPOINT uvicorn --host 0.0.0.0 main:app --reload